default_language_version:
  python: python3.7
exclude: '^.idea\/'
repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
    exclude: '(test_.+|conftest)\.py'
    language_version: python3.7
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: flake8
    args:
    - --max-line-length=88
  - id: trailing-whitespace
    exclude: '.+\.md'
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.4.3
  hooks:
  - id: pylint
    exclude: '(test_.+|conftest)\.py'
    args:
    - --disable=bad-continuation  # When pylint and black squabble.
    - --disable=fixme  # Allow TODO comments
    - --disable=import-error  # pylint plugin has trouble with virtualenv imports
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.7
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
- repo: https://github.com/KPilnacek/mirrors-bandit
  rev: 44a8790d12e9767ab946ddd9704c22cdd29479d6
  hooks:
  - id: bandit
